services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=admin
      - DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.37
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: